# Generated by Django 5.2.1 on 2025-09-03 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplChain_MNG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='code_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='code_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplChain_MNG.material'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplChain_MNG.material'),
        ),
    ]
