# Generated by Django 5.2.1 on 2025-09-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplChain_MNG', '0003_project_materialreturn_requisition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreturn',
            name='code_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialreturn',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SupplChain_MNG.material'),
        ),
    ]
