# Generated by Django 5.2.1 on 2025-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplChain_MNG', '0004_materialreturn_code_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code_number',
            field=models.CharField(default='UNKNOWN', max_length=50, unique=True),
        ),
    ]
