# Generated by Django 5.2.1 on 2026-04-10 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0005_alter_material_code_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("license_number", models.CharField(max_length=60, unique=True)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="material",
            name="is_consumable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="measurement_unit",
            field=models.CharField(
                choices=[
                    ("UNIT", "Units"),
                    ("L", "Litres"),
                    ("ML", "Millilitres"),
                    ("G", "Grams"),
                    ("KG", "Kilograms"),
                    ("TON", "Tonnes"),
                ],
                default="UNIT",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="MobileEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("registration_number", models.CharField(max_length=60, unique=True)),
                ("equipment_type", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("BREAKDOWN", "Breakdown"),
                            ("REPAIRING", "Repairing"),
                            ("SERVICED", "Serviced"),
                            ("PARKED", "Parked"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("current_location", models.CharField(blank=True, max_length=200)),
                ("current_route_from", models.CharField(blank=True, max_length=120)),
                ("current_route_to", models.CharField(blank=True, max_length=120)),
                ("odometer_reading", models.PositiveIntegerField(default=0)),
                ("service_due_date", models.DateField(blank=True, null=True)),
                ("road_tax_due_date", models.DateField(blank=True, null=True)),
                ("fitness_due_date", models.DateField(blank=True, null=True)),
                ("insurance_due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SupplChain_MNG.driver",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SupplChain_MNG.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FleetMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service"),
                            ("REPAIR", "Repair"),
                            ("BREAKDOWN", "Breakdown"),
                            ("FITNESS", "Fitness Check"),
                        ],
                        default="SERVICE",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("service_provider", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplChain_MNG.mobileequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FleetFuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fluid_type",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("OIL", "Oil"),
                            ("GREASE", "Grease"),
                        ],
                        default="FUEL",
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("UNIT", "Units"),
                            ("L", "Litres"),
                            ("ML", "Millilitres"),
                            ("G", "Grams"),
                            ("KG", "Kilograms"),
                            ("TON", "Tonnes"),
                        ],
                        default="L",
                        max_length=8,
                    ),
                ),
                ("odometer_at_fill", models.PositiveIntegerField(default=0)),
                ("from_location", models.CharField(blank=True, max_length=120)),
                ("to_location", models.CharField(blank=True, max_length=120)),
                (
                    "date_logged",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "consumable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SupplChain_MNG.material",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplChain_MNG.mobileequipment",
                    ),
                ),
            ],
        ),
    ]
