# Generated by Django 5.2.1 on 2026-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0006_driver_material_is_consumable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="materials/documents/"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="materials/photos/"
            ),
        ),
    ]
