# Generated by Django 5.2.1 on 2026-04-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0007_material_document_material_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="equipment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SupplChain_MNG.project",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IN_USE", "In Use"),
                    ("MAINTENANCE", "Maintenance"),
                    ("BROKEN", "Broken"),
                    ("STORED", "Stored"),
                ],
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
