# Generated by Django 5.2.1 on 2026-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0008_equipment_is_active_equipment_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="equipment/documents/"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="equipment/photos/"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="service_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
