# Generated by Django 5.2.1 on 2026-04-12 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0011_requisitionreadreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("HQ", "Main Warehouse"),
                            ("SITE", "Site Store"),
                            ("SCRAP", "Scrap Yard"),
                            ("SUPPLIER", "Supplier Transit"),
                        ],
                        default="SITE",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_locations",
                        to="SupplChain_MNG.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorageBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bin_code", models.CharField(max_length=3)),
                ("zone", models.CharField(blank=True, max_length=40)),
                ("aisle", models.CharField(blank=True, max_length=40)),
                ("rack", models.CharField(blank=True, max_length=40)),
                ("shelf", models.CharField(blank=True, max_length=40)),
                ("description", models.CharField(blank=True, max_length=180)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bins",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["store_location__name", "bin_code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Receipt"),
                            ("ISSUE", "Issue"),
                            ("TRANSFER", "Transfer"),
                            ("RETURN", "Return"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference_type", models.CharField(blank=True, max_length=40)),
                ("reference_number", models.CharField(blank=True, max_length=60)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_movements",
                        to="SupplChain_MNG.material",
                    ),
                ),
                (
                    "from_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="SupplChain_MNG.storagebin",
                    ),
                ),
                (
                    "to_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="SupplChain_MNG.storagebin",
                    ),
                ),
                (
                    "from_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
                (
                    "to_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_hand",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reserved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balances",
                        to="SupplChain_MNG.material",
                    ),
                ),
                (
                    "storage_bin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balances",
                        to="SupplChain_MNG.storagebin",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "material__name",
                    "storage_bin__store_location__name",
                    "storage_bin__bin_code",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("material", "storage_bin"),
                        name="unique_material_balance_per_bin",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="storagebin",
            constraint=models.UniqueConstraint(
                fields=("store_location", "bin_code"), name="unique_bin_per_store"
            ),
        ),
    ]
