# Generated by Django 5.2.1 on 2026-04-12 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SupplChain_MNG",
            "0014_deliverynote_approved_at_deliverynote_approved_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                (
                    "date_received",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("HQ", "HQ Transfer"),
                            ("SUPPLIER", "Supplier Delivery"),
                            ("SITE", "Site Transfer"),
                        ],
                        default="HQ",
                        max_length=12,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("prepared_by", models.CharField(max_length=120)),
                ("delivered_by", models.CharField(max_length=120)),
                ("received_by", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("stock_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_delivery_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SupplChain_MNG.deliverynote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=220)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_returnable", models.BooleanField(default=False)),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="SupplChain_MNG.goodsreceipt",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SupplChain_MNG.material",
                    ),
                ),
            ],
        ),
    ]
