# Generated by Django 5.2.1 on 2026-04-12 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0015_goodsreceipt_goodsreceiptitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                (
                    "date_issued",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("department", models.CharField(blank=True, max_length=120)),
                ("issued_to", models.CharField(max_length=120)),
                ("issued_by", models.CharField(max_length=120)),
                ("received_by", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("stock_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_issues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_issues_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_issues",
                        to="SupplChain_MNG.storagebin",
                    ),
                ),
                (
                    "source_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_issues",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsIssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=220)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_returnable", models.BooleanField(default=False)),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                (
                    "goods_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="SupplChain_MNG.goodsissue",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SupplChain_MNG.material",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                (
                    "date_returned",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("returned_by", models.CharField(max_length=120)),
                ("received_by", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("stock_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_returns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_returns_in",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
                (
                    "from_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_returns_out",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_returns_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_goods_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="SupplChain_MNG.goodsissue",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("DAMAGED", "Damaged"),
                            ("SCRAP", "Scrap"),
                        ],
                        default="GOOD",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=220)),
                (
                    "goods_issue_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_items",
                        to="SupplChain_MNG.goodsissueitem",
                    ),
                ),
                (
                    "goods_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="SupplChain_MNG.goodsreturn",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SupplChain_MNG.material",
                    ),
                ),
            ],
        ),
    ]
