# Generated by Django 5.2.1 on 2026-04-12 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0016_goodsissue_goodsissueitem_goodsreturn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="store_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_items",
                to="SupplChain_MNG.storelocation",
            ),
        ),
        migrations.AddField(
            model_name="mobileequipment",
            name="store_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mobile_equipment_items",
                to="SupplChain_MNG.storelocation",
            ),
        ),
        migrations.CreateModel(
            name="PPEIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                (
                    "date_issued",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("employee_name", models.CharField(max_length=140)),
                ("employee_number", models.CharField(blank=True, max_length=60)),
                ("department", models.CharField(blank=True, max_length=120)),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full PPE Kit"),
                            ("PARTIAL", "Partial PPE"),
                            ("REPLACEMENT", "Replacement"),
                        ],
                        default="FULL",
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NEW", "New Assignment"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("WEAR", "Wear and Tear"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("approved_by", models.CharField(blank=True, max_length=120)),
                ("issued_by", models.CharField(max_length=120)),
                ("received_by", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("stock_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_issues_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_issues_posted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_bin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_issues",
                        to="SupplChain_MNG.storagebin",
                    ),
                ),
                (
                    "store_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppe_issues",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PPEIssueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("size_spec", models.CharField(blank=True, max_length=60)),
                ("notes", models.CharField(blank=True, max_length=220)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SupplChain_MNG.material",
                    ),
                ),
                (
                    "ppe_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="SupplChain_MNG.ppeissue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStoreScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage", models.BooleanField(default=True)),
                (
                    "store_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scopes",
                        to="SupplChain_MNG.storelocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username", "store_location__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "store_location"),
                        name="unique_user_store_scope",
                    )
                ],
            },
        ),
    ]
