# Generated by Django 5.2.1 on 2026-04-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0017_equipment_store_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="req_number",
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="quantity_requested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RequisitionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=220)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="SupplChain_MNG.material",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="SupplChain_MNG.requisition",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
    ]
