# Generated by Django 5.2.1 on 2026-04-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0018_requisition_req_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovement",
            name="delivery_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="SupplChain_MNG.deliverynote",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="SupplChain_MNG.driver",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="mobile_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to="SupplChain_MNG.mobileequipment",
            ),
        ),
    ]
