# Generated by Django 5.2.1 on 2026-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0019_inventorymovement_delivery_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="serial_number",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
