# Generated by Django 5.2.1 on 2026-05-04 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0021_warehouse_and_storelocation_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="destination_bin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_receipts",
                to="SupplChain_MNG.storagebin",
            ),
        ),
    ]
