# Generated by Django 5.2.1 on 2026-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0022_goodsreceipt_destination_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybalance",
            name="min_required",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum stock threshold for this material in this warehouse bin.",
                max_digits=12,
            ),
        ),
    ]
