# Generated by Django 5.2.1 on 2026-05-07 09:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0023_inventorybalance_min_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="quantity_fulfilled",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Actual quantity delivered to destination",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="sla_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Target fulfillment deadline for accountability tracking",
                null=True,
            ),
        ),
    ]
