# Generated by Django 5.2.1 on 2026-05-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0024_requisition_quantity_fulfilled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="destination_warehouse_or_site",
            field=models.CharField(
                blank=True,
                help_text="Name of destination warehouse or project/site",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="driver",
            field=models.CharField(
                blank=True,
                help_text="Name of the driver transporting goods",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="mobile_equipment",
            field=models.CharField(
                blank=True,
                help_text="Vehicle registration, asset tag, or equipment ID",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="reference_number",
            field=models.CharField(
                blank=True, help_text="Reference document number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="reference_type",
            field=models.CharField(
                blank=True,
                help_text="Type of reference (e.g., PO, Invoice, Work Order)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="source_warehouse_or_site",
            field=models.CharField(
                blank=True,
                help_text="Name of source warehouse or project/site",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="transfer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAREHOUSE_TO_SITE", "Warehouse to Site"),
                    ("SITE_TO_WAREHOUSE", "Site to Warehouse"),
                    ("SITE_TO_SITE", "Site to Site"),
                    ("WAREHOUSE_TO_WAREHOUSE", "Warehouse to Warehouse"),
                    ("INTERNAL", "Internal Transfer"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of transfer being performed",
                max_length=30,
            ),
        ),
    ]
