# Generated by Django 5.2.1 on 2026-05-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SupplChain_MNG", "0025_deliverynote_destination_warehouse_or_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="destination_warehouse_or_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Select destination warehouse or project/site store",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes_as_destination",
                to="SupplChain_MNG.storelocation",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="source_warehouse_or_site",
            field=models.ForeignKey(
                blank=True,
                help_text="Select source warehouse or project/site store",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes_as_source",
                to="SupplChain_MNG.storelocation",
            ),
        ),
    ]
