# Generated by Django 5.2.1 on 2026-05-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SupplChain_MNG",
            "0026_alter_deliverynote_destination_warehouse_or_site_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynote",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Select a driver from fleet management",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes",
                to="SupplChain_MNG.driver",
            ),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="mobile_equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Select vehicle/equipment from fleet management",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_notes",
                to="SupplChain_MNG.mobileequipment",
            ),
        ),
    ]
